import tempfile
import os
from fpdf import FPDF
from datetime import datetime

class PDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 15)
        self.cell(0, 10, 'Blood Infection Early Detection Report', 0, 1, 'C')
        self.set_font('Helvetica', 'I', 10)
        self.cell(0, 10, f'Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_report(patient_data, risk_score, risk_level, insights):
    """
    patient_data is a dict containing patient details.
    Returns path to the generated PDF file.
    """
    pdf = PDF()
    pdf.add_page()
    
    # Patient Info Section
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 10, 'Patient Information', 0, 1, 'L')
    pdf.set_font('Helvetica', '', 11)
    
    for key, value in patient_data.items():
        pdf.cell(50, 8, str(key), 0, 0)
        pdf.cell(0, 8, str(value), 0, 1)
        
    pdf.ln(5)
    
    # Prediction Results
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 10, 'Prediction Results', 0, 1, 'L')
    
    pdf.set_font('Helvetica', '', 11)
    pdf.cell(50, 8, 'Infection Risk Score:', 0, 0)
    # Highlight score based on level
    if risk_level == 'High':
        pdf.set_text_color(200, 0, 0)
    elif risk_level == 'Medium':
        pdf.set_text_color(200, 150, 0)
    else:
        pdf.set_text_color(0, 150, 0)
        
    pdf.cell(0, 8, f'{risk_score}%', 0, 1)
    
    pdf.set_text_color(0, 0, 0)
    pdf.cell(50, 8, 'Risk Category:', 0, 0)
    pdf.cell(0, 8, f'{risk_level}', 0, 1)
    
    pdf.ln(5)
    
    # Health Recommendations / Insights
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 10, 'Health Insights & Recommendations', 0, 1, 'L')
    
    pdf.set_font('Helvetica', '', 11)
    pdf.multi_cell(0, 8, insights)
    
    pdf.ln(5)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 10, 'Action Needed', 0, 1, 'L')
    pdf.set_font('Helvetica', '', 11)
    
    pdf.ln(10)
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 6, "Disclaimer: This report is generated by an Artificial Intelligence system for diagnostic support and decision-assistance only. AI results are not a substitute for clinical analysis by a certified medical doctor. Please consult with a healthcare professional to correlate these findings with clinical observations.")
    
    # Generate temp file
    fd, temp_path = tempfile.mkstemp(suffix='.pdf')
    os.close(fd)
    
    # Output
    pdf.output(temp_path)
    return temp_path
